---
# yaml-language-server: $schema=https://k8s-skeemahs.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: housefam-casa
spec:
  dnsNames:
    - housefam.casa
    - "*.housefam.casa"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: housefam-casa-tls
  usages:
    - digital signature
