---
# yaml-language-server: $schema=https://k8s-skeemahs.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft
  interval: 1h
  values:
    fullnameOverride: *app
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2026.1.0-java25-graalvm@sha256:57390cb09b3450551bed092d4e60328e991ca556ad28296efb944aa010460ec0
      pullPolicy: IfNotPresent
    livenessProbe:
      initialDelaySeconds: 120
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: &hostname mc.thefryer.games
      external-dns.alpha.kubernetes.io/target: mc-router.thefryer.games
      gatus.home-operations.com/endpoint: |-
        group: services
      mc-router.itzg.me/externalServerName: *hostname
    minecraftServer:
      difficulty: "hard"
      eula: "true"
      forcegameMode: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      maxPlayers: 10
      maxWorldSize: 29999984
      motd: "The Fryer's Minecraft Server"
      ops: "FryyourBacon"
      overrideServerProperties: true
      removeOldMods: true
      spawnProtection: 0
      type: "FABRIC"
      vanillaTweaksShareCodes:
        - f8rjVA
        - FF8soj
      version: "1.21.11"
      viewDistance: 7
      rcon:
        enabled: true
        existingSecret: &secret minecraft-secret
        secretKey: RCON_PASSWORD
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft
    extraEnv:
      ALLOW_FLIGHT: "true"
      ENABLE_ROLLING_LOGS: "true"
      ENFORCE_WHITELIST: "true"
      MEMORY: ""
      OVERRIDE_WHITELIST: "true"
      PACKWIZ_URL: "https://raw.githubusercontent.com/caycehouse/fabulously-optimized-server/refs/tags/${PACKWIZ_VERSION}/pack.toml"
      RCON_CMDS_STARTUP: |-
        gamerule minecraft:fire_spread_radius_around_player 0
        gamerule minecraft:players_sleeping_percentage 0
        scoreboard objectives setdisplay list ts_Deaths
      SIMULATION_DISTANCE: "4"
      SNOOPER_ENABLED: "false"
      SYNC_CHUNK_WRITES: "false"
      USE_MEOWICE_FLAGS: "true"
      USE_MEOWICE_GRAALVM_FLAGS: "true"
    envFrom:
      - secretRef:
          name: *secret
    resources:
      requests:
        cpu: 500m
        memory: &mem 6Gi
      limits:
        memory: *mem
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
