---
# yaml-language-server: $schema=https://k8s-skeemahs.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-ddns-secret
    template:
      data:
        ACCOUNT_TOKEN: "{{ .CLOUDFLARE_DNS_TOKEN }}"
  dataFrom:
  - extract:
      key: cloudflare
