---
# yaml-language-server: $schema=https://k8s-skeemahs.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: satisfactory
spec:
  endpoints:
    - dnsName: "valheim.thefryer.games"
      recordType: CNAME
      targets: ["ipv4.housefam.casa"]
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
