---
# yaml-language-server: $schema=https://k8s-skeemahs.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hytale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hytale-secret
    template:
      data:
        MACHINE_ID: "{{ .HYTALE_MACHINE_ID }}"
  dataFrom:
    - extract:
        key: hytale
