---
# yaml-language-server: $schema=https://k8s-skeemahs.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: itzg
  namespace: flux-system
spec:
  interval: 12h
  url: https://itzg.github.io/minecraft-server-charts
